name: Dynamic Package Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          echo "Finding package directories..."
          PACKAGES=$(find . -maxdepth 1 -type d -exec test -e '{}/requirements.txt' \; -print | sed 's|^\./||' | jq -R . | jq -cs .)
          echo "matrix=${PACKAGES}" >> $GITHUB_OUTPUT

  lint-test:
    needs: list-packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.list-packages.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"
          cache: "pip"

      - name: Install dependencies for ${{ matrix.package }}
        run: |
          if [ -f ${{ matrix.package }}/requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r ${{ matrix.package }}/requirements.txt
          fi
          pip install ruff==0.1.0

      - name: Lint with ruff (selected rules) in ${{ matrix.package }}
        run: |
          ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py311 ${{ matrix.package }}
          ruff --output-format=github --target-version=py311 ${{ matrix.package }}

      - name: Test with unittest in ${{ matrix.package }}
        run: |
          cd ${{ matrix.package }}
          python -m unittest discover -s tests
        env:
          FINESSE_BACKEND_AZURE_SEARCH_ENDPOINT: ${{ secrets.FINESSE_BACKEND_AZURE_SEARCH_ENDPOINT }}
          FINESSE_BACKEND_AZURE_SEARCH_API_KEY: ${{ secrets.FINESSE_BACKEND_AZURE_SEARCH_API_KEY }}
          FINESSE_BACKEND_AZURE_SEARCH_INDEX_NAME: ${{ secrets.FINESSE_BACKEND_AZURE_SEARCH_INDEX_NAME }}

  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with:
      config-file-path: ".mlc_config.json"
    secrets: inherit

  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
